### PR TITLE
Missing ItemizedStats.msg build.

### PR DESCRIPTION
**Pull request by JBot**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@JBot, thanks for the contribution.  I'm curious if you intend to use the `ItemizedStats` message?  The ROS API has been well thought out, but since it wasn't even in the `CMakeLists`, it's clear it was never used.

**Comment by minlingc** [comment]
Hi @JBot , 

Can you explain abit more about what help you need with this ?

Thanks, Min Ling

**Comment by minlingc** [comment]
@jbot, definitely not abandoned, we are working on this, hence it is still active.

would you like to help contribute as well ?

**Comment by shaun-edwards** [comment]
This project is active, but the priority/holdup is the replacement of the underlying state machine framework: https://github.com/ros-industrial-consortium/packml/issues/17.  We just haven't had an available resource with the C++ capability/know how to address this issue.  

Once this is accomplished, we intend to roll out the more features/development.  PackML statistics (https://github.com/ros-industrial-consortium/packml/issues/24) is high on the list.

**Pull request merged**
