### PR TITLE
Run Service Calls in a Separate Thread

### PR DESCRIPTION
**Pull request by geoffreychiou**
@joshuaplusone please review.

### CODE REVIEW

**Review by joshuaplusone — APPROVED** [review]
Approved

**Comment by geoffreychiou** [comment]
@shaun-edwards please merge when you get a chance.

**Comment by shaun-edwards** [comment]
I can't believe that took more than 4 lines...python disappoints ;)

Thanks @geoffreychiou for the updates

**Comment by gavanderhoorn** [comment]
Could either @geoffreychiou, @joshuaplusone or @shaun-edwards provide some rationale for this change? What does it fix? IIRC, according to documentation, `rospy` already spins off threads for incoming events?

**Comment by joshuaplusone** [comment]
@gavanderhoorn we were solving for an issue where spamming the service calls from the buttons was causing the UI to lock up and packml to crash. Our solution was to push outgoing service calls triggered by the buttons off of the UI thread so it wouldn't block the UI while they were running.

**Comment by gavanderhoorn** [comment]
Ah, that makes sense.

From a quick look I had not understood these were service clients.

Yeah, not using the UI thread for that is better.

**Pull request merged**
